image:
  - Visual Studio 2019
  - Ubuntu
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
    - sh: sudo ./build.sh
    
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
    - ps: . ./build.ps1
deploy: off