image:
  - Visual Studio 2019
  # - Ubuntu
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - ps: dotnet build Nancy.Serialization.Hyperion.sln
test_script:
  - ps: dotnet test ./tests/Nancy.Serialization.Hyperion.Tests -c Release
# for:
# -
#   matrix:
#     only:
#       - image: Ubuntu

#   build_script:
#     - sh: sudo dotnet build Nancy.Serialization.Hyperion.sln

#   test_script:
#     - sh: sudo ./build.sh
deploy: off